{{ if .Values.authentication.passwordEntries }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.authentication.passwordEntries }}
  passwordfile: {{ toYaml .Values.authentication.passwordEntries | b64enc | quote }}
  {{- end }}
{{- end }}